package org.dieschnittstelle.jee.esa.erp.ejbs.crud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-02-01T17:07:31.293+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", name = "ProductCRUDRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductCRUDRemote {

    @WebMethod
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.CreateProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dieschnittstelle.jee.esa.erp.ejbs.crud.AbstractProduct createProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.erp.ejbs.crud.AbstractProduct arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.DeleteProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.UpdateProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dieschnittstelle.jee.esa.erp.ejbs.crud.AbstractProduct updateProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.erp.ejbs.crud.AbstractProduct arg0
    );

    @WebMethod
    @RequestWrapper(localName = "readAllProducts", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.ReadAllProducts")
    @ResponseWrapper(localName = "readAllProductsResponse", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.ReadAllProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.dieschnittstelle.jee.esa.erp.ejbs.crud.AbstractProduct> readAllProducts();

    @WebMethod
    @RequestWrapper(localName = "readProduct", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.ReadProduct")
    @ResponseWrapper(localName = "readProductResponse", targetNamespace = "http://crud.ejbs.erp.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.erp.ejbs.crud.ReadProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.dieschnittstelle.jee.esa.erp.ejbs.crud.AbstractProduct readProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
